# 例外処理

例外処理について学ぶ。  
scalaでの例外処理は、方法として以下がある。

* try-catch
* Option
* Either
* Try

それぞれの使い方を見ていく。

## 1. try-catch

Javaと同様に使うことができる。

```scala
try {
  処理A
} catch {
  case 変数1: ExceptionClass1 => 式1
  case 変数2: ExceptionClass2 => 式2
  ...
}
```

catch節には "case e:Exception => ..."のようなパターンマッチを書くことで、対応する例外の型に応じて処理することができる。try,catchを評価した結果は、実行されたブロックで最後に評価された式の値になる。

例
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

val n = try{ "test".toInt } catch {
   case e:NumberFormatException => -9
   case e:Exception => -99
}

// Exiting paste mode, now interpreting.

n: Int = -9

// 参考
// 「"test".toInt」は「NumberFormatException」の例外を出す
scala> "test".toInt
java.lang.NumberFormatException: For input string: "test"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:580)
  at java.lang.Integer.parseInt(Integer.java:615)
  at scala.collection.immutable.StringLike.toInt(StringLike.scala:301)
  at scala.collection.immutable.StringLike.toInt$(StringLike.scala:301)
  at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
  ... 28 elided
```

finally節も同様に指定できる。ただし、finally節で評価された値は捨てられる。

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

val n = try{ "test".toInt } catch {
  case e:Exception => println("test");2
}
finally{
  println("finally");0
}

// Exiting paste mode, now interpreting.

<pastie>:15: warning: a pure expression does nothing in statement position
  println("finally");0
                     ^
<pastie>:15: warning: multiline expressions might require enclosing parentheses; a value can be silently discarded when Unit is expected
  println("finally");0
                     ^
test
finally
n: Int = 2
```

Scalaにおける例外は、Javaとは異なり非チェック例外となる。Java側のAPIでthrows宣言されているメソッドをScalaから呼び出しても、コンパイルエラーにはならない。

下の例は、JavaではFileNotFoundExceptionをcatchする必要があるが、Scalaではcatchしなくてもコンパイルエラーにならない。

```scala
scala> val test = new java.io.FileInputStream("test.txt")
java.io.FileNotFoundException: test.txt (No such file or directory)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at java.io.FileInputStream.<init>(FileInputStream.java:93)
  ... 28 elided

```

また、Scalaでは、メソッドの宣言時にthrows節で例外を明示することはできない。
Javaでは下記のようにthrows節で呼ばれる側に例外を投げる処理を明示できた。

```
void testB () throws FileNotFoundException {
    FileReader r = new FileReader(“sample.txt”);
    System.out.print(“ファイルを読み込みました”);
}
void testC () {
    try {
        testB();
    } catch (FileNotFoundException e) {
        System.out.print(“ファイルが存在しませんでした”);
    }
}
```

## 2. Option

### 2.1. 基本的な使い方

Optionは値があるかないかわからない場合に、ラップして返してくれるもの。値がある場合はSome()に値が包まれて返り、ない場合はNoneが返ってくる。

```scala
scala> val test = Option("hoge")
test: Option[String] = Some(hoge)

scala> :paste
// Entering paste mode (ctrl-D to finish)

val result = test match {
  case Some(str) => str
  case None => "not matched"
}

// Exiting paste mode, now interpreting.

result: String = hoge
```

### 2.2. 例外処理での使われ方

よく使われているのが、Mapなどのコレクションを使用するケース。
Mapでgetメソッドを使用して値を取得した値は、Option型となる。

```scala
scala> val map = Map("Japan" -> "Tokyo", "France" -> "Paris")
map: scala.collection.immutable.Map[String,String] = Map(Japan -> Tokyo, France -> Paris)

scala> map.get("France")
res11: Option[String] = Some(Paris)

scala> map.get("America")
res12: Option[String] = None

scala> :paste
// Entering paste mode (ctrl-D to finish)

map.get("key") match {
  case Some(x) => x
  case None => "none"
}

// Exiting paste mode, now interpreting.

res9: String = none

scala> :paste
// Entering paste mode (ctrl-D to finish)

map.get("Japan") match {
  case Some(x) => x
  case None => "none"
}

// Exiting paste mode, now interpreting.

res10: String = Tokyo
```

他の使用ケースとしては、あるJavaのメソッドでnullを返す可能性がある場合、そのメソッドをOptionで包むケース。

Option(someJavaApi()) とすればjavaのAPIが返すnullをOptionのNoneとして扱うことができる。

```scala
Option(someJavaApi()) match {
  case Some(x) => x
  case None => "none"
}
```

## 3. Either

### 3.1. 基本的な使い方

Either型は、ふたつの型の値をもつ可能性があることを示す型。Option型と同様に、Either型自身は抽象クラスで、サブタイプとしてLeft型とRight型を持つ。

下記の例のようにEither[Int,String]型で型指定した場合、LeftではInt型の値を持ち、RightではString型の値を持つ。

```scala
scala> val v1: Either[Int, String] = Left(123)
v1: Either[Int,String] = Left(123)

scala> val v2: Either[Int, String] = Right("abc")
v2: Either[Int,String] = Right(abc)

scala> :paste
// Entering paste mode (ctrl-D to finish)

v1 match {
  case Right(i) => println(i);println("Right")
  case Left(s)  => println(s);println("Left")
}

// Exiting paste mode, now interpreting.

123
Left
```

### 3.2. 例外処理での使われ方

一般的に、Left値をエラー値、Right値を正常な値とみなして使用する。

以下の例のfileInputStreamメソッドはEitherを返し、引数の値のファイルが存在しない場合に、Left値にエラーを、ファイルが存在する場合はRight値でFileInputStreamの結果を返している。

```scala
scala> import java.io._
import java.io._

scala> :paste
// Entering paste mode (ctrl-D to finish)

def fileInputStream(filename:String):Either[FileNotFoundException,FileInputStream] = {
  try{
     Right( new FileInputStream(filename) )
  }catch{
     case e:FileNotFoundException => Left(e)
  }
}

// Exiting paste mode, now interpreting.

fileInputStream: (filename: String)Either[java.io.FileNotFoundException,java.io.FileInputStream]

scala> fileInputStream("test.txt")
res0: Either[java.io.FileNotFoundException,java.io.FileInputStream] = Right(java.io.FileInputStream@7a682d35)

scala> fileInputStream("test")
res1: Either[java.io.FileNotFoundException,java.io.FileInputStream] = Left(java.io.FileNotFoundException: test (No such file or directory))
```

どんなエラーかを含めて返したい場合、Eitherを利用する。Eitherは成功したらRightに値を入れ、失敗したらLeftにエラーを入れて返すことで、呼び出し元で例外処理できる。
エラーの処理が漏れているかどうかをコンパイラが検知することにも利用できる。

以下、エラーを定義し、エラー処理の考慮漏れが見られる例

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

sealed trait LoginError
// パスワードが間違っている場合のエラー
case object InvalidPassword extends LoginError
// nameで指定されたユーザーが見つからない場合のエラー
case object UserNotFound extends LoginError

case class User(id: Long, name: String, password: String)

object LoginService {
  def login(name: String, password: String): Either[LoginError, User] = {
    if (password != "password") {
      Left(InvalidPassword)
    } else if (name != "tarou") {
      Left(UserNotFound)
    } else {
      Right(User(id=1, name, password))
    }
  }
}

// Exiting paste mode, now interpreting.

defined trait LoginError
defined object InvalidPassword
defined object UserNotFound
defined class User
defined object LoginService

scala> :paste
// Entering paste mode (ctrl-D to finish)

LoginService.login(name = "test", password = "password") match {
  case Right(user) => println(s"id: ${user.id}")
  case Left(InvalidPassword) => println(s"Invalid Password!")
}

// Exiting paste mode, now interpreting.

<pastie>:14: warning: match may not be exhaustive.
It would fail on the following input: Left(UserNotFound)
LoginService.login(name = "test", password = "password") match {
                  ^
scala.MatchError: Left(UserNotFound) (of class scala.util.Left)
  ... 36 elided

```

考慮漏れを修正

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

LoginService.login(name = "test", password = "password") match {
  case Right(user) => println(s"id: ${user.id}")
  case Left(InvalidPassword) => println(s"Invalid Password!")
  case Left(UserNotFound) => println(s"User Not Found!")
}

// Exiting paste mode, now interpreting.

User Not Found!
```

## 4. Try

scala2.10.0以降で使える機能。

TryはSuccess[T]とFailure[Throwable]という派生クラスを持ち、処理が成功した場合はSuccess、例外が発生した場合でNonFatal(致命的ではない)な場合はFailureが返る。

NonFatalではない、つまり致命的だと判断されるのは以下の例外。

* VirtualMachineError
* ThreadDeath
* InterruptedException
* LinkageError
* ControlThrowable

これらの例外が発生した場合は、Failureではなくそのまま例外がスローされる。

Eitherとの違いは、2つの型が平等ではなく、エラー値がThrowableに限定されており、型引数を1つしか取らないこと。
例外が起こりそうな箇所をTryで包み、Failureとして値として扱えるようにすることがTryの特徴。

使用する際はimportが必要。

```scala
scala> import scala.util.{Try, Success, Failure}
import scala.util.{Try, Success, Failure}

scala> val v = Try(1)
v: scala.util.Try[Int] = Success(1)

scala> val v = Try("test")
v: scala.util.Try[String] = Success(test)

scala> val v: Try[Int] = Try(throw new RuntimeException("to be caught"))
v: scala.util.Try[Int] = Failure(java.lang.RuntimeException: to be caught)

```

パターンマッチで値の取得可能。

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

v match {
  case Success(i) => println(i)
  case Failure(s)  => println(s)
}

// Exiting paste mode, now interpreting.

java.lang.RuntimeException: to be caught

```

参考)Tryで得た値の計算
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

val sum = for {
  int1 <- Try(Integer.parseInt("1"))
  int2 <- Try(Integer.parseInt("2"))
} yield {
  int1 + int2
}

// Exiting paste mode, now interpreting.

sum: scala.util.Try[Int] = Success(3)

scala> :paste
// Entering paste mode (ctrl-D to finish)

val sum = for {
  int1 <- Try(Integer.parseInt("1"))
  int2 <- Try(Integer.parseInt("test"))
} yield {
  int1 + int2
}

// Exiting paste mode, now interpreting.

sum: scala.util.Try[Int] = Failure(java.lang.NumberFormatException: For input string: "test")

```

## 5. 使い分けまとめ

基本はtry-catch

メソッドの返り値がnullになる可能性がある場面でOption

エラーの内容を取得したい場面でEither

例外をどうしても値として扱いたい場面でTry

## 補足 OptionやEither、Tryの演算について

演算はflatMapやmapを使用する方法とfor yield を使用する方法がある。

Optionの例

```scala
scala> val op1 = Option(1)
op1: Option[Int] = Some(1)

scala> val op2 = Option(2)
op2: Option[Int] = Some(2)

scala> val op3 = Option(null)
op3: Option[Null] = None

# flatMapやmapでの例
scala> :paste
// Entering paste mode (ctrl-D to finish)

op1.flatMap(a =>
  op2.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

3
res0: Option[Int] = Some(3)

scala> :paste
// Entering paste mode (ctrl-D to finish)

op1.flatMap(a =>
  op3.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

res1: Option[String] = None

# for yieldでの例
scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- op1
  b <- op2
} yield a + b

// Exiting paste mode, now interpreting.

res20: Option[Int] = Some(3)

scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- op1
  b <- op3
} yield a + b

// Exiting paste mode, now interpreting.

res21: Option[String] = None
```

Eitherの例

```scala
scala> val ei1: Either[Int, String] = Right("a")
ei1: Either[Int,String] = Right(a)

scala> val ei2: Either[Int, String] = Right("b")
ei2: Either[Int,String] = Right(b)

scala> val ei3: Either[Int, String] = Left(2)
ei3: Either[Int,String] = Left(2)

scala> val ei4: Either[Int, String] = Left(3)
ei4: Either[Int,String] = Left(3)

# flatMapやmapでの例
scala> :paste
// Entering paste mode (ctrl-D to finish)

ei1.right.flatMap(a =>
  ei2.right.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

ab
res23: scala.util.Either[Int,String] = Right(ab)

scala> :paste
// Entering paste mode (ctrl-D to finish)

ei3.left.flatMap(a =>
  ei4.left.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

5
res24: scala.util.Either[Int,String] = Left(5)

scala> :paste
// Entering paste mode (ctrl-D to finish)

ei1.right.flatMap(a =>
  ei3.left.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

a2
res26: scala.util.Either[Any,String] = Left(a2)

# leftのものをrightとして演算しようとした場合、演算されず、leftの値が返る
scala> :paste
// Entering paste mode (ctrl-D to finish)

ei1.right.flatMap(a =>
  ei3.right.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

res35: scala.util.Either[Int,String] = Left(2)

# for yieldでの例
scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- ei1.right
  b <- ei2.right
} yield a + b

// Exiting paste mode, now interpreting.

res36: scala.util.Either[Int,String] = Right(ab)

scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- ei1.right
  b <- ei3.left
} yield a + b

// Exiting paste mode, now interpreting.

res37: scala.util.Either[Any,String] = Left(a2)

scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- ei1.right
  b <- ei3.right
} yield a + b

// Exiting paste mode, now interpreting.

res38: scala.util.Either[Int,String] = Left(2)
```

Tryの例

```scala
scala> val tr1 = Try(1)
tr1: scala.util.Try[Int] = Success(1)

scala> val tr2 = Try(2)
tr2: scala.util.Try[Int] = Success(2)

scala> val tr3:Try[Int] = Try(throw new RuntimeException("to be caught"))
tr3: scala.util.Try[Int] = Failure(java.lang.RuntimeException: to be caught)

# flatMapやmapでの例
scala> :paste
// Entering paste mode (ctrl-D to finish)

tr1.flatMap(a =>
  tr2.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

3
res0: scala.util.Try[Int] = Success(3)

scala> :paste
// Entering paste mode (ctrl-D to finish)

tr1.flatMap(a =>
  tr3.map(b => {
    println(a + b)
    a + b
  })
)

// Exiting paste mode, now interpreting.

res2: scala.util.Try[Int] = Failure(java.lang.RuntimeException: to be caught)

# for yieldでの例
scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- tr1
  b <- tr2
} yield a + b

// Exiting paste mode, now interpreting.

res40: scala.util.Try[Int] = Success(3)

scala> :paste
// Entering paste mode (ctrl-D to finish)

for {
  a <- tr1
  b <- tr3
} yield a + b

// Exiting paste mode, now interpreting.

res41: scala.util.Try[Int] = Failure(java.lang.RuntimeException: to be caught)

scala>
```
